### ISSUE TITLE
OSError: Unable to open file (File signature not found)

### ISSUE THREAD

**Issue by SeventhBlue** [lq010/Online-Detection-of-Action-Start#2]
This project is very interesting,Thanks to bloggers for sharing. When I started training I got an error as shown in the title. Indicates that the model(sports1M_weights_tf.h5) has been damaged. Can you send a copy，please?(weizhen1218951642@gmail.com or weizhenmo@qq.com)Or suggest how to get it.

**Comment by lq010** [comment]
Hi, you can download it here 
https://drive.google.com/open?id=1vkSw6yKe4CCq4SYBPmoTofVlXj-MBYms

**Comment by SeventhBlue** [comment]
thanks，i got it！
